name: Unit test run
on:
  workflow_dispatch:
  push:
    branches:
      - development
      - alpha
      - production
      - "[a-zA-Z]+/[0-9]+-*"
      - "[a-zA-Z]+/[0-9]+_*"
      - "[0-9]+-*"
      - "[0-9]+_*"

jobs:
  UnitTests:
    name: Unit tests
    timeout-minutes: 18
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Print scheduled unit test run
        run: echo "This is a scheduled unit-test run."

      - name: checkout branch default
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run unit tests
        run: npm run test:all

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Print scheduled unit test complete
        run: echo "Unit test run completed"
